### PR TITLE
Fixed styling for Alert component

### PR DESCRIPTION
**Pull request by sushma-priyadharssini**
Fixes [#356](https://github.com/weaveworks/ui-components/issues/356)

### CODE REVIEW

**Comment by visualapps** [comment]
@sushma-priyadharssini looks good to me. Please attach screenshot of alerts component.

**Comment by sushma-priyadharssini** [comment]
Screenshot before my fix:
alertbox_before_fix
Screenshot after my fix:
alertbox_after_fix

**Comment by sushma-priyadharssini** [comment]
Yes.. I have mentioned in the description.

**Comment by farhaanbukhsh** [comment]
Can you make the text a little bold, it's really hard to read I feel we should make it clearer.

**Comment by sushma-priyadharssini** [comment]
Well, That was not part of the issue. It looks shrunken when uploaded here. Just click on the image and see. I guess It looks fine.

**Pull request merged**
