### PR TITLE
Update a number of deps to address security issues

### PR DESCRIPTION
**Pull request by dholbach**
update postcss, stylelint-declaration-use-variable, webpack, webpack-dev-server, node-sass, standard-version, trim-newlines, stylelint, enzyme, babel and babel-jest

### CODE REVIEW

**Comment by jpellizzari** [comment]
@dholbach I don't see any security advisories on this repo. Was there a reason for this PR?

**Comment by dholbach** [comment]
Did you check the dependabot alerts?

**Comment by jpellizzari** [comment]
> Did you check the dependabot alerts?

I don't see a link to that anywhere in the repo.

**Comment by dholbach** [comment]
Maybe you need to ask Corp IT for privileges - I saw a list there. :-/

**Review by jpellizzari — APPROVED** [review]

**Pull request merged**
