### PR TITLE
workaround for dropdown item label title `[object Object]`

### PR DESCRIPTION
**Pull request by dimitropoulos**
Screenshot_20190322_123747

The above UI bug can happen in a situation where the label passed in is an object since objects are truthy in javascript.  Ideally, Flow should catch this kind of problem but since it doesn't (from what I can tell the type gets lost as it goes through the `lodash/find` on line 200), a type check here will work for now.

### CODE REVIEW

**Comment by rndstr** [comment]
@errordeveloper the problem is that the eksctl within `weaveworks/eksctl:0.1.25` has no version

```
 $ docker run weaveworks/eksctl:0.1.25 eksctl version
[ℹ]  version.Info{BuiltAt:"1553524352", GitCommit:"0.1.25-dirty", GitTag:""}
```

**Comment by dimitropoulos** [comment]
thanks @rndstr - I'll hopefully be setting up my environment for javascript dev soon enough but you saved me from having to do it now :)

**Comment by fbarl** [comment]
ping @dimitropoulos - anything still blocking you from merging this?

**Comment by dimitropoulos** [comment]
no - merging now.

**Pull request merged**
